### ISSUE TITLE
Trino workers autoscaling

### ISSUE THREAD

**Issue by adwiza** [stackabletech/trino-lb#12]
Hi, we need to scale up and down the Trino workers in Trino cluster, can we use this to to solve this issue, or we need to use an alternative approach, could you please cheet to us how to deal with Trino workers autoscaling?

**Comment by sbernauer** [comment]
Hi @adwiza, I personally would argue it's the responsibility of the Trino cluster itself to scale the number of workers based on e.g. number of running/queued queries, CPU or some other metric. But I'm also happy about feedback, if you have different opinions.

E.g. at Stackable we will probably utilize [Horizontal Pod Autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) for that, created https://github.com/stackabletech/trino-operator/issues/532 for that

The community helm-chart of Trino uses the mentioned approach once you enable `server.autoscaling.enabled` [docs](https://github.com/trinodb/charts/blob/2c1d97b20b86c41cffcaf4c0105330be490c9554/charts/trino/README.md)

**Comment by adwiza** [comment]
Hi @sbernauer I haven't mentioned, but that we are using the Trino operator and I guess this solution doesn't fit for us, isn't it?

**Comment by sbernauer** [comment]
Sorry, did I get it correctly that you are using https://github.com/stackabletech/trino-operator? In this case you sadly need to wait for https://github.com/stackabletech/trino-operator/issues/532 to have auto-scaling for the workers.

**Comment by adwiza** [comment]
Yes it is, we are using the https://github.com/stackabletech/trino-operator 
    productVersion: "428"
    stackableVersion: "23.11.0"

**Comment by adwiza** [comment]
@soenkeliebau it works, thank you, I've added the HPA configuration with needed behavior that's all

**Comment by soenkeliebau** [comment]
That is great to hear, thank you for reporting back!

**Comment by NickLarsenNZ** [comment]
Closing in favour of https://github.com/stackabletech/trino-operator/issues/532
